#!/bin/bash

run () {
  local ruu_size=$1

  # echo -n "ruu_size,$ruu_size"
  export SSFLAGS="-ruu:size $ruu_size"
  ./run-wattch 2>&1 | awk "/sim_IPC/ {printf(\"ruu_size,$ruu_size,sim_IPC,%s\n\",\$2)};"
}

for ruu_size in 2 4 8 16 32 64 128 256
do
  run "$ruu_size" &
done

wait

# time ./scripts/varyarch
# ruu_size,002,sim_IPC,0.5173
# ruu_size,004,sim_IPC,0.8494
# ruu_size,008,sim_IPC,1.2066
# ruu_size,016,sim_IPC,1.3065
# ruu_size,032,sim_IPC,1.3089
# ruu_size,064,sim_IPC,1.3090
# ruu_size,128,sim_IPC,1.3090
# ruu_size,256,sim_IPC,1.3090

# real    0m50.242s
# user    5m52.940s
# sys     0m0.330s

# time ./scripts/varyarch
# ruu_size,2,sim_IPC,0.5173
# ruu_size,4,sim_IPC,0.8494
# ruu_size,8,sim_IPC,1.2066
# ruu_size,16,sim_IPC,1.3065
# ruu_size,32,sim_IPC,1.3089
# ruu_size,64,sim_IPC,1.3090
# ruu_size,128,sim_IPC,1.3090
# ruu_size,256,sim_IPC,1.3090

# real    3m51.124s
# user    3m50.988s
# sys     0m0.056s